Document: piktomir
Title: Debian piktomir Manual
Author: <insert document author here>
Abstract: This manual describes what piktomir is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/piktomir/piktomir.sgml.gz

Format: postscript
Files: /usr/share/doc/piktomir/piktomir.ps.gz

Format: text
Files: /usr/share/doc/piktomir/piktomir.text.gz

Format: HTML
Index: /usr/share/doc/piktomir/html/index.html
Files: /usr/share/doc/piktomir/html/*.html
